
"""Initial migration

Revision ID: 86aa40f33ea7
Revises: 
Create Date: 2026-05-24 23:25:11.709453

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00_00_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bettors',
    sa.Column('proxy_wallet', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('proxy_wallet'),
    sa.UniqueConstraint('name'),
    if_not_exists=True,
    )
    op.create_table('users',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=True),
    sa.Column('lastname', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('registered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_tg_id'),
    if_not_exists=True,
    )
    op.create_table('subscriptions',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('bettor_id', sa.String(length=42), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bettor_id'], ['bettors.proxy_wallet'], ondelete="CASCADE", onupdate="CASCADE"),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ondelete="CASCADE", onupdate="CASCADE"),
    sa.PrimaryKeyConstraint('uid'),
    if_not_exists=True,
    )
    op.create_table('bettor_stats',
    sa.Column('uid', sa.String(length=42), nullable=False),
    sa.Column('last_trade_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_trades_count', sa.Integer(), nullable=False),
    sa.Column('current_trades_count', sa.Integer(), nullable=False),
    sa.Column('closed_trades_volume', sa.Float(), nullable=False),
    sa.Column('winnings', sa.Float(), nullable=False),
    sa.Column('current_trades_volume', sa.Float(), nullable=False),
    sa.Column('winrate', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['bettors.proxy_wallet'], ondelete="CASCADE", onupdate="CASCADE"),
    sa.PrimaryKeyConstraint('uid'),
    if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions', if_exists=True)
    op.drop_table('bettor_stats', if_exists=True)
    op.drop_table('users', if_exists=True)
    op.drop_table('bettors', if_exists=True)
    # ### end Alembic commands ###